development:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIB7XBE2XDOQMTSTA
  S3_SECRET: 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

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIB7XBE2XDOQMTSTA
  S3_SECRET: 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

production:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIB7XBE2XDOQMTSTA
  S3_SECRET: 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