development:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAI2EWJXYBLMT2WHCA
  S3_SECRET: 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

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAI2EWJXYBLMT2WHCA
  S3_SECRET: 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

production:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAI2EWJXYBLMT2WHCA
  S3_SECRET: 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