development:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIK4U7V67NHWIOSQA
  S3_SECRET: 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

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIK4U7V67NHWIOSQA
  S3_SECRET: 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

production:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIK4U7V67NHWIOSQA
  S3_SECRET: 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