development:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIZA3SESL3OZIUUIA
  S3_SECRET: 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

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIZA3SESL3OZIUUIA
  S3_SECRET: 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

production:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
  S3_KEY: AKIAIZA3SESL3OZIUUIA
  S3_SECRET: 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