development:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw

production:
  STRIPE_PUBLISHABLE_KEY: pk_test_4XEDLOwV6urVOihKjdvILVvb
  STRIPE_SECRET_KEY: sk_test_4XEDZACDjx28MH3mRygFsCNw
